name: Gemini Config
version: 1.0.0
schema: v1

models:
  - name: Gemini 2.5 Pro
    provider: gemini
    model: gemini-2.5-pro
    apiKey: YOUR_GEMINI_API_KEY

  - name: Gemini 2.5 Flash
    provider: gemini
    model: gemini-2.5-flash
    apiKey: AQ.Ab8RN6JwWBDfKDzabMiHvnwQxHyVYznPbxEGmDwwas8VeuzhGw